# Generated by Django 3.2.13 on 2022-06-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
