# Generated by Django 3.2.13 on 2022-06-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=6, verbose_name='nombre')),
                ('marca', models.CharField(max_length=10, verbose_name='marca')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
