# Generated by Django 3.2.13 on 2022-06-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nombre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='nombre'),
        ),
    ]
