# Generated by Django 3.2.13 on 2022-06-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_users_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contraseña',
            field=models.IntegerField(verbose_name='contrasena'),
        ),
    ]
